#!/bin/bash

# Переменная наличия флага --all
USE_CLONE_ALL_BRANCHES="$1"


# Путь к директории для кэша
CACHE_DIR="/tmp/gclfzf_cache"
# Создаем директорию для кэша, если она не существует
mkdir -p "$CACHE_DIR"

# Время жизни кэша в минутах
CACHE_LIFETIME=3600
# Очистка старых файлов кэша
echo "[X] Очистка старых файлов кэша..."
find "$CACHE_DIR" -type f -mmin +"$CACHE_LIFETIME" -exec rm -f {} \; &


# Файл для кэша количества страниц
PAGES_CACHE_FILE="$CACHE_DIR/pages_count.cache"


# Функция для проверки и установки переменных окружения
setup_env_vars() {
  local var_name
  var_name="$1"
  local value
  value=$(printenv "$var_name")

  if [[ -z "$value" ]]; then
    echo "Переменная окружения $var_name не найдена."
    read -p "Введите значение для $var_name: " value
    if [[ -z "$value" ]]; then
      echo "Значение не может быть пустым. Скрипт завершается."
      exit 1
    fi
    export "$var_name"="$value"
  fi
}

# Вызов функции для проверки и установки переменных окружения
setup_env_vars "GL_DOMAIN"
setup_env_vars "GL_TOKEN"
GL_URL="$GL_DOMAIN//api/v4/projects"

# Функция для проверки наличия команды
check_command() {
  local command_name="$1"
  if ! command -v "$command_name" &>/dev/null; then
    echo "$command_name не найден. Установите $command_name и повторите."
    exit 1
  fi
}

# Вызов функции для проверки наличия jq
check_command "jq"
# Вызов функции для проверки наличия fzf
check_command "fzf"
# Вызов функции для проверки наличия curl
check_command "curl"

# Функция для получения количества страниц и записи в кэш
get_number_of_pages() {
  echo "==> Получение количества страниц с репозиториями GitLab..."
  local number_of_pages
  number_of_pages=$(curl -m 10 -s --head --header "PRIVATE-TOKEN: $GL_TOKEN" "$GL_URL?per_page=100" |
    grep -i x-total-pages | awk '{print $2}' | tr -d '\r\n')

  if [[ -z "$number_of_pages" ]]; then
    echo "Не удалось получить данные с ${GL_DOMAIN}. Команда завершается."
    exit 1
  fi
  # Сохраняем количество страниц в кэш
  echo "$number_of_pages" > "$PAGES_CACHE_FILE"
  echo "$number_of_pages"
}

# Получение количества страниц из кэша или с сервера
if [ -f "$PAGES_CACHE_FILE" ]; then
  # Если файл кэша существует и актуален, используем его
  number_of_pages=$(<"$PAGES_CACHE_FILE")
else
  # Иначе получаем количество страниц и кэшируем
  number_of_pages=$(get_number_of_pages)
fi

# Инициализация массива для хранения URL-ов репозиториев
declare -a repo_urls
# Заполнение массива URL-ами репозиториев
for page in $(seq 1 "$number_of_pages"); do
  cache_file="$CACHE_DIR/$(echo -n "$GL_URL?page=$page&per_page=100" | md5sum | cut -d' ' -f1)"
  if [ -f "$cache_file" ]; then
    # Если файл кэша существует, читаем его напрямую
    mapfile -t page_urls < "$cache_file"
  else
    # Получение данных с сервера и сохранение в кэш
    response=$(curl -m 30 -s --header "PRIVATE-TOKEN: $GL_TOKEN" "$GL_URL?per_page=100&page=$page")
    mapfile -t page_urls < <(echo "$response" | jq -r '.[] | "\(.name)|\(.ssh_url_to_repo)"' | sed 's/ /_/g')
    printf "%s\n" "${page_urls[@]}" > "$cache_file"
  fi
  repo_urls+=("${page_urls[@]}")

  # Вывод прогресс-бара
  echo -ne "Заполнение массива: [${page}/${number_of_pages}]\r"
done
echo -ne "\n"

# Передача массива в fzf для выбора
selected_repo=$(for repo in "${repo_urls[@]}"; do echo "$repo" |
  sed 's/|/ -> /'; done |
  fzf --preview 'echo {}' --preview-window=up:1)

border() {
  title="| $1 |"
  edge=$(echo "$title" | sed 's/./-/g')
  echo "$edge"
  echo "$title"
  echo "$edge"
}

# Вывод выбранного репозитория
border "Выбранный репозиторий: $selected_repo"

repo_name=$(echo "$selected_repo" | awk -F' -> ' '{print $1}')
repo_url=$(echo "$selected_repo" | awk -F' -> ' '{print $2}')

if [[ -z "$repo_url" ]]; then
  echo "==> URL пустой. Команда завершена."
  exit 1
fi

clone-mirror() {
  local url
  url=$1
  local repo_name
  repo_name=$(basename "$url" .git)

  git clone --mirror "$url" "./$repo_name/.git"
  (
    cd "$repo_name" || exit 1
    git config --bool core.bare false
    git reset --hard
  )
}

# Клонирование выбранного репозитория
if [[ "$USE_CLONE_ALL_BRANCHES" == "--all" ]]; then
  echo "Клонирование репозитория $repo_name со всеми ветками..."
  clone-mirror "$repo_url"
else
  echo "Клонирование репозитория $repo_name..."
  git clone "$repo_url"
fi

echo "==> Клонирование завершено"
exit 0
